#!/usr/bin/env bash
# Install and configure HAproxy on your server.

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
    	balance roundrobin
	server 496279-web-01 100.25.204.76:80 check
	server 496279-web-02 54.234.78.120:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
