#!/usr/bin/env bash
# Install and configure HAproxy on your server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
    backend web-backend
    	balance roundrobin
	server 496279-web-01 100.26.223.120
	server 496279-web-02 100.26.18.64" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
