#!/usr/bin/env bash
# A Bash script that:
#	Creates the file /var/run/myscript.pid containing its PID.
#	Displays To infinity and beyond indefinitely.
#	Displays I hate the kill command when receiving a SIGTERM signal.
#	Displays Y U no love me?! when receiving a SIGINT signal.
#	Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

sigterm_signal(){
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

sigint_signal(){
	echo "Y U no love me?!"
}

sigquit_signal(){
	rm /var/run/myscript.pid
	exit
}

trap 'sigterm_signal' SIGTERM
trap 'sigint_signal' SIGINT
trap 'sigquit_signal' SIGQUIT


echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
