#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely.
# Requirements:
#	In between each iteration of the loop, add a sleep 2.
#	Display I am invincible!!! when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
