#!/usr/bin/env bash
#script that displays the content of the file.
# Your script should only display:
#	username.
#	user id.
#	Home directory path for the user.

while IFS=":" read -r username password id group info home_dir shell
do
	echo "The user $username is part of the $group gang, lives in $home_dir and rides $shell. $id's place is protected by the passcode $password, more info about the user here: $info"

done < /etc/passwd
