#!/usr/bin/env bash
# Setting up Client configuration file.
# must be configured to use the private key ~/.ssh/school.
# must be configured to refuse to authenticate using a password.

Host 100.26.223.120
    IdentityFile ~/.ssh/school
    Protocol 2
    PasswordAuthentication no
